n=input('digite algo')
print(n.isalpha())
n=input('digite algo')
print(n.isnumeric())
n=input('digite algo')
print(n.isupper())
n=input('digite algo')
print(n.islower())
n=input('digite algo')
print(n.isdigit())
n=input('digite algo')